export enum MedicalRecordType {
  // Consultas
  CONSULTATION = 'CONSULTATION',
  CONSULTATION_RETURN = 'CONSULTATION_RETURN',

  // Atestados
  CERTIFICATE_HEALTH = 'CERTIFICATE_HEALTH',
  CERTIFICATE_DEATH = 'CERTIFICATE_DEATH',
  CERTIFICATE_VACCINE = 'CERTIFICATE_VACCINE',
  CERTIFICATE_TRANSPORT = 'CERTIFICATE_TRANSPORT',

  // Termos
  TERM_SURGERY = 'TERM_SURGERY',
  TERM_ANESTHESIA = 'TERM_ANESTHESIA',
  TERM_EUTHANASIA = 'TERM_EUTHANASIA',
  TERM_HOSPITALIZATION = 'TERM_HOSPITALIZATION',

  // Documentos clinicos
  PRESCRIPTION = 'PRESCRIPTION',
  SURGICAL_REPORT = 'SURGICAL_REPORT',
  EUTHANASIA_REPORT = 'EUTHANASIA_REPORT',
  EXAM_RESULT = 'EXAM_RESULT',
  OTHER = 'OTHER',
}
