export enum ServiceCategory {
  BATH = 'BATH',
  GROOMING = 'GROOMING',
  VETERINARY = 'VETERINARY',
  VACCINATION = 'VACCINATION',
  TRAINING = 'TRAINING',
  DAYCARE = 'DAYCARE',
  BOARDING = 'BOARDING',
  TRANSPORT = 'TRANSPORT',
  OTHER = 'OTHER',
}
