import '../../core/domain/enums/animal_species.dart';

const Map<AnimalSpecies, List<String>> animalBreeds = {
  AnimalSpecies.dog: [
    'Sem raça definida (SRD)',
    'Labrador Retriever',
    'Golden Retriever',
    'Bulldog Francês',
    'Bulldog Inglês',
    'Poodle',
    'Shih Tzu',
    'Yorkshire Terrier',
    'Dachshund',
    'Beagle',
    'Rottweiler',
    'Pastor Alemão',
    'Husky Siberiano',
    'Doberman',
    'Chow Chow',
    'Akita',
    'Border Collie',
    'Cocker Spaniel',
    'Maltês',
    'Spitz Alemão',
    'Boxer',
  ],
  AnimalSpecies.cat: [
    'Sem raça definida (SRD)',
    'Persa',
    'Siamês',
    'Maine Coon',
    'Sphynx',
    'Ragdoll',
    'Bengal',
    'British Shorthair',
    'Scottish Fold',
    'Angorá',
    'Himalaio',
    'Azul Russo',
    'Abissínio',
    'Burmês',
    'Devon Rex',
    'Cornish Rex',
    'Savannah',
    'Oriental Shorthair',
    'Somali',
    'Tonquinês',
    'Chartreux',
  ],
  AnimalSpecies.bird: [
    'Sem raça definida (SRD)',
    'Calopsita',
    'Canário',
    'Periquito Australiano',
    'Agapornis',
    'Cacatua',
    'Arara Azul',
    'Arara Vermelha',
    'Papagaio',
    'Papagaio do Congo',
    'Diamante Mandarim',
    'Diamante de Gould',
    'Curió',
    'Trinca-ferro',
    'Coleiro',
    'Pintassilgo',
    'Mainá',
    'Lóris',
    'Rosela',
    'Faisão',
    'Codorna',
  ],
  AnimalSpecies.fish: [
    'Sem raça definida (SRD)',
    'Betta',
    'Guppy',
    'Neon Tetra',
    'Platy',
    'Molinésia',
    'Espada',
    'Acará Bandeira',
    'Acará Disco',
    'Oscar',
    'Kinguio',
    'Carpa Koi',
    'Corydora',
    'Tetra Negro',
    'Barbo Tigre',
    'Danio',
    'Ramirezi',
    'Peixe Anjo',
    'Cascudo',
    'Killifish',
    'Aruanã',
  ],
  AnimalSpecies.reptile: [
    'Sem raça definida (SRD)',
    'Iguana Verde',
    'Gecko Leopardo',
    'Gecko Tokay',
    'Dragão Barbudo',
    'Camaleão',
    'Jabuti',
    'Tartaruga Tigre d\'Água',
    'Corn Snake',
    'Jiboia',
    'Píton',
    'Teiú',
    'Lagarto Monitor',
    'Skink',
    'Anolis',
    'Cobra Rei',
    'Dragão d\'Água',
    'Uromastyx',
  ],
  AnimalSpecies.horse: [
    'Sem raça definida (SRD)',
    'Mangalarga Marchador',
    'Mangalarga Paulista',
    'Quarto de Milha',
    'Puro Sangue Inglês',
    'Árabe',
    'Crioulo',
    'Appaloosa',
    'Paint Horse',
    'Andaluz',
    'Lusitano',
    'Frísio',
    'Percheron',
    'Shire',
    'Clydesdale',
    'Mustang',
    'Hanoveriano',
    'Holsteiner',
    'Selle Français',
    'Tennessee Walker',
    'Campolina',
  ],
  AnimalSpecies.cow: [
    'Sem raça definida (SRD)',
    'Nelore',
    'Angus',
    'Hereford',
    'Brahman',
    'Gir',
    'Girolando',
    'Holandês',
    'Jersey',
    'Simental',
    'Charolês',
    'Limousin',
    'Guzerá',
    'Tabapuã',
    'Senepol',
    'Canchim',
    'Bonsmara',
    'Brangus',
    'Caracu',
    'Devon',
    'Santa Gertrudis',
  ],
};
